language: node_js
node_js:
  - 12
compiler:
  - gcc
env:
  - CXX="g++-4.9"
  - CC="gcc-4.9"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5 # not sure why we needed this
    packages:
      - gcc-4.9
      - g++-4.9
services:
  - docker
after_success:
  - docker build -t vatusa/tmu-bot .
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then docker tag vatusa/tmu-bot vatusa/tmu-bot:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push vatusa/tmu-bot:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then docker tag vatusa/tmu-bot vatusa/tmu-bot:devel;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push vatusa/tmu-bot:devel;
    fi